baseURL: 'http://plord.co.uk/'
languageCode: 'en-us'
title: 'Peter Lord'
theme: 'ananke'
pluralizeListTitles: false
Paginate: 5
copyright: Except where otherwise noted, the content on this site is licensed under a Creative Commons Attribution-ShareAlike 4.0 International Licence.

params:
  read_more_copy: Read more about this entry
  date_format: "2. January 2006"
  recent_posts_number: 3
  background_color_class: "bg-blue"
  ananke_socials:
  - name: email
    url: mailto:peter@plord.co.uk
    color: black
  - name: signal
    url: https://signal.me/#p/+447867970260
    color: black
  - name: telegram
    url: https://telegram.me/PeterLord
    color: black
  - name: github
    url: https://github.com/plord12
  - name: discord
    url: https://discordapp.com/users/plord#7168
  - name: rss
    url: https://plord.co.uk/index.xml
  #- name: apple
  #  url: imessage://peter@plord.co.uk

menu:
  main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Links
    pageRef: /links
    weight: 10
  - name: Talks
    pageRef: /talks
    weight: 10
